AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  discord-slash-command-processor
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DISCORD_PUBLIC_KEY: ''

Resources:
  DiscordSlashCommandProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: processor/src/handler.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - arm64
      Events:
        PlayerCreate:
          Type: Api
          Properties:
            Path: /slash-command
            Method: post

#Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#  HelloWorldFunction:
#    Description: "Hello World Lambda Function ARN"
#    Value: !GetAtt HelloWorldFunction.Arn
#  HelloWorldFunctionIamRole:
#    Description: "Implicit IAM Role created for Hello World function"
#    Value: !GetAtt HelloWorldFunctionRole.Arn
